server:
  port: 9527

spring:
  application:
    name: cloud-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

  instance:
    hostname: cloud-gateway-service

