server:
  port: 9527

spring:
  application:
    name: cloud-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          # spring.cloud.gateway.discovery.locator.enabled：是否与服务注册于发现组件进行结合，通过 serviceId 转发到具体的服务实例。默认为 false，设为 true 便开启通过服务中心的自动根据 serviceId 创建路由的功能。
          # spring.cloud.gateway.discovery.locator.lowerCaseServiceId：是将请求路径上的服务名配置为小写（因为服务注册的时候，向注册中心注册时将服务名转成大写的了）。
          enabled: true
          lower-case-service-id: true
      routes:
        - id: payment_route1
          # uri: http://localhost:8001
          uri: lb://cloud-payment-service # 表示不是直接的地址，而是负载均衡的，需要去注册中心找
          predicates:
            - Path=/payment/get/{id} # 或者/payment/get/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

  instance:
    hostname: cloud-gateway-service