server:
  port: 7002
spring:
  application:
    name: cloud-eureka-server-7002
eureka:
  instance:
    hostname: eureka7002.com #eureka服务端的实例名称
    # 指示eureka客户端需要多长时间(以秒为单位)向eureka服务器发送一次心跳，以表明它仍处于活动状态。默认30秒
    # 如果在leaseExpirationDurationInSeconds中指定的时间内没有接收到心跳，eureka服务器将从其视图中删除该实例，并禁止该实例的流量。
    #lease-renewal-interval-in-seconds: 1
    # 指示eureka客户端需要多长时间(以秒为单位)向eureka服务器发送一次心跳，以表明它仍处于活动状态。默认90秒
    # 如果在leaseExpirationDurationInSeconds中指定的时间内没有接收到心跳，eureka服务器将从其视图中删除该实例，并禁止该实例的流量。
    #lease-expiration-duration-in-seconds: 2
  client:
    #false表示不向注册中心注册自己。
    register-with-eureka: false
    #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址。
      #集群就是相互注册对方的url
      defaultZone: http://eureka7001.com:7001/eureka/
  # 默认开启自我保护
  #server:
    #enable-self-preservation: false
    # 设置 检测下线服务 驱逐时间间隔 默认是60s
    #eviction-interval-timer-in-ms: 2000